# Generated by Django 4.2.17 on 2025-01-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name of cinema')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_cinema/', verbose_name='Pictures')),
                ('view', models.IntegerField(default=0, verbose_name='Views')),
                ('description', models.TextField(verbose_name='Content')),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created cinema')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update cinema')),
                ('rating', models.FloatField(verbose_name='Rating of cinema')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
